### ISSUE TITLE
Build fails on zbar > 0.20

### ISSUE THREAD

**Issue by rffontenelle** [magiclen/zbar-rust#3]
zbar-rust currently requires zbar <= 0.20 to be installed in the system, otherwise the build fails with `ZBar version must be no higher than 0.20`.  Arch Linux has [zbar] 0.23.1, and the 3-years-old version 0.20.0 doesn't seem to build with gtk3-based dependencies and Python 3.9.

See build log for [Authenticator], which depends on zbar-rust: [build-output-authenticator.txt](https://github.com/magiclen/zbar-rust/files/5793317/build-output-authenticator.txt)

Can the required version be raised so zbar-rust can build on Arch Linux and [other distros]?

[zbar]: https://archlinux.org/packages/extra/x86_64/zbar/
[Authenticator]: https://gitlab.gnome.org/World/Authenticator
[other distros]: https://repology.org/project/zbar/versions

**Comment by Tuxino88** [comment]
paradoxically zbar is also old (at least 4 years old)

**Comment by tytan652** [comment]
It doesn't fail, it just don't want to build because it's set to not build against versions beyond 0.20
The developement of zbar is active [here](https://github.com/mchehab/zbar)
Why did you limit the max version or zbar ?

**Comment by rffontenelle** [comment]
@tytan652 I did not limit the max version. Such limit is set on [build.rs](https://github.com/magiclen/zbar-rust/blob/master/build.rs#L154), and is causing the build failure / it not wanting to build (call it whatever you want).

**Comment by tytan652** [comment]
Sorry for the misunderstanding, the question was asked to the developer itself not you.

**Comment by magiclen** [comment]
Sorry for the inconvenience. The max version limitation has been removed since `0.0.16`. ([zbar 0.23.90](https://github.com/mchehab/zbar/releases) seems work fine)

**Comment by tytan652** [comment]
Thank you

**Comment by rffontenelle** [comment]
Thanks @magiclen !

**Comment by rffontenelle** [comment]
Just for reference:  fc38e762
